version: '3'
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - ./consul/:/consul/data
  tracing:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - consul
    environment:
      - DB=consul
      - DBPORT=8500
      - JAEGER_SERVICE_NAME=posts
      - JAEGER_AGENT_HOST=tracing
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger:5778
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus-data:/prometheus
volumes:
  consul:
  prometheus-data: